import { ReactComponent as ParameterDist } from "../assets/icons/parameter-distribution.svg";
import { ReactComponent as ParameterDist2 } from "../assets/icons/parameter-distribution2.svg";
import { ReactComponent as TheoriesComparison } from "../assets/icons/theories-comparison.svg";
import { ReactComponent as TheoryDriven } from "../assets/icons/theory-driven.svg";
import { ReactComponent as ParameterTheory } from "../assets/icons/parameter&theory.svg";
import { ReactComponent as Trends } from "../assets/icons/trends.svg";
import { ReactComponent as Timings } from "../assets/icons/timing.svg";
import { ReactComponent as Frequencies } from "../assets/icons/frequencies.svg";
import { ReactComponent as Journals } from "../assets/icons/journals.svg";
import { ReactComponent as AnatomicalFindings } from "../assets/icons/anatomical-findings.svg";
import { ReactComponent as WorldMap } from "../assets/icons/consciousness-world-map.svg";

export const screenWidth = window.screen.width;
export const screenHeight = window.screen.height;
export const navHeight = 80;
export const sideWidth = 370;
export const sideSectionClass =
  "w-full border-b border-grayReg py-5 flex flex-col items-center gap-3 ";

export const isMoblile = screenWidth < 600;

export const parametersOptions = [
  {
    value: "paradigm_family",
    label: "Paradigm Family",
  },
  {
    value: "paradigm",
    label: "Paradigm",
  },
  {
    value: "population",
    label: "Population",
  },
  {
    value: "finding_tag",
    label: "Finding Tag",
  },
  {
    value: "finding_tag_family",
    label: "Finding Tag Family",
  },
  {
    value: "reporting",
    label: "Reporting",
  },
  {
    value: "theory_driven",
    label: "Theory Driven",
  },
  {
    value: "task",
    label: "Task",
  },
  {
    value: "stimuli_category",
    label: "Stimuli Category",
  },
  {
    value: "modality",
    label: "Modality",
  },
  {
    value: "consciousness_measure_phase",
    label: "Consciousness Measure Phase",
  },
  {
    value: "consciousness_measure_type",
    label: "Consciousness Measure Type",
  },
  {
    value: "type_of_consciousness",
    label: "Type of Consciousness",
  },
  {
    value: "technique",
    label: "Technique",
  },
  {
    value: "measure",
    label: "Measure",
  },
];
export const available_techniques_for_timings = [
  { value: "EEG", label: "EEG" },
  { value: "MEG", label: "MEG" },
  { value: "TMS", label: "TMS" },
  { value: "Computational Modelling", label: "Computational Modelling" },
];

export const AlphaBetaColors = {
  Alpha: "#C2549D",
  Beta: "#EB5A88",
  Gamma: "#EF7576",
  Delta: "#4D3991",
  Theta: "#8949A2",
};
export const colorsArray = [
  "rgba(189, 183, 89, 1)",
  "rgba(196, 137, 87, 1)",
  "rgba(202, 83, 90, 1)",
  "rgba(164, 92, 150, 1)",
  "rgba(116, 88, 160, 1)",
  "rgba(73, 107, 155, 1)",
  "rgba(62, 127, 148, 1)",
  "rgba(34, 109, 116, 1)",
  "rgba(66, 153, 134, 1)",
  "rgba(79, 180, 89, 1)",
  "rgba(241, 192, 232,1)",
  "rgba(255, 215, 0, 1)",
  "rgba(240, 128, 128, 1)",
  "rgba(176, 196, 222, 1)",
  "rgba(255, 160, 122, 1)",
];
export const myColors = [
  "AliceBlue",
  "AntiqueWhite",
  "Aqua",
  "Aquamarine",
  "Azure",
  "Beige",
  "Bisque",
  "Black",
  "BlanchedAlmond",
  "Blue",
  "BlueViolet",
  "Brown",
  "BurlyWood",
  "CadetBlue",
  "Chartreuse",
  "Chocolate",
  "Coral",
  "CornflowerBlue",
  "Cornsilk",
  "Crimson",
  "Cyan",
  "DarkBlue",
  "DarkCyan",
  "DarkGoldenRod",
  "DarkGray",
  "DarkGrey",
  "DarkGreen",
  "DarkKhaki",
  "DarkMagenta",
  "DarkOliveGreen",
  "DarkOrange",
  "DarkOrchid",
  "DarkRed",
  "DarkSalmon",
  "DarkSeaGreen",
  "DarkSlateBlue",
  "DarkSlateGray",
  "DarkSlateGrey",
  "DarkTurquoise",
  "DarkViolet",
  "DeepPink",
  "DeepSkyBlue",
  "DimGray",
  "DimGrey",
  "DodgerBlue",
  "FireBrick",
  "FloralWhite",
  "ForestGreen",
  "Fuchsia",
  "Gainsboro",
  "GhostWhite",
  "Gold",
  "GoldenRod",
  "Gray",
  "Grey",
  "Green",
  "GreenYellow",
  "HoneyDew",
  "HotPink",
  "IndianRed",
  "Indigo",
  "Ivory",
  "Khaki",
  "Lavender",
  "LavenderBlush",
  "LawnGreen",
  "LemonChiffon",
  "LightBlue",
  "LightCoral",
  "LightCyan",
  "LightGoldenRodYellow",
  "LightGray",
  "LightGrey",
  "LightGreen",
  "LightPink",
  "LightSalmon",
  "LightSeaGreen",
  "LightSkyBlue",
  "LightSlateGray",
  "LightSlateGrey",
  "LightSteelBlue",
  "LightYellow",
  "Lime",
  "LimeGreen",
  "Linen",
  "Magenta",
  "Maroon",
  "MediumAquaMarine",
  "MediumBlue",
  "MediumOrchid",
  "MediumPurple",
  "MediumSeaGreen",
  "MediumSlateBlue",
  "MediumSpringGreen",
  "MediumTurquoise",
  "MediumVioletRed",
  "MidnightBlue",
  "MintCream",
  "MistyRose",
  "Moccasin",
  "NavajoWhite",
  "Navy",
  "OldLace",
  "Olive",
  "OliveDrab",
  "Orange",
  "OrangeRed",
  "Orchid",
  "PaleGoldenRod",
  "PaleGreen",
  "PaleTurquoise",
  "PaleVioletRed",
  "PapayaWhip",
  "PeachPuff",
  "Peru",
  "Pink",
  "Plum",
  "PowderBlue",
  "Purple",
  "Red",
  "RosyBrown",
  "RoyalBlue",
  "SaddleBrown",
  "Salmon",
  "SandyBrown",
  "SeaGreen",
  "SeaShell",
  "Sienna",
  "Silver",
  "SkyBlue",
  "SlateBlue",
  "SlateGray",
];

export const designerColors = [
  "#FBF8CC",
  "#FDE4CF",
  "#FFCFD2",
  "#F1C0E8",
  "#CFBAF0",
  "#A3C4F3",
  "#90DBF4",
  "#8EECF5",
  "#98F5E1",
  "#B9FBC0",
  "#E6E2A6",
  "#EAC6A7",
  "#EDA6AA",
  "#D79FCD",
  "#B199D5",
  "#85A6D6",
  "#75BCD4",
  "#73CCD5",
  "#7BD6C3",
  "#96E39E",
  "#D2CC7F",
  "#D7A77F",
  "#DB7C82",
  "#BD7DB2",
  "#9379BB",
  "#6789B9",
  "#5A9DB4",
  "#58ACB5",
  "#5FB8A5",
  "#72CC7C",
  "#BDB759",
  "#C48957",
  "#CA535A",
  "#A45C96",
  "#7458A0",
  "#496B9B",
  "#3E7F94",
  "#3D8D94",
  "#429986",
  "#4FB459",
  "#B3AC46",
  "#BB7A43",
  "#C13E46",
  "#974B89",
  "#654893",
  "#3A5C8D",
  "#316F84",
  "#307D84",
  "#348A77",
  "#3DA848",
  "#A9A132",
  "#B16A2F",
  "#B82932",
  "#8A3A7B",
  "#563886",
  "#2B4E7E",
  "#236074",
  "#226D74",
  "#267B68",
  "#2B9D37",
  "#9E961F",
  "#A85B1B",
  "#AF151E",
  "#7D2A6E",
  "#472778",
  "#1C3F70",
  "#165064",
  "#155D64",
  "#176B59",
  "#1A9126",
  "#948B0C",
  "#9E4C07",
  "#A6000A",
  "#701960",
  "#38176B",
  "#0D3061",
  "#084154",
  "#074D54",
  "#095C4A",
  "#088515",
  "#FBF8CC",
  "#FDE4CF",
  "#FFCFD2",
  "#F1C0E8",
  "#CFBAF0",
  "#A3C4F3",
  "#90DBF4",
  "#8EECF5",
  "#98F5E1",
  "#B9FBC0",
  "#E6E2A6",
  "#EAC6A7",
  "#EDA6AA",
  "#D79FCD",
  "#B199D5",
  "#85A6D6",
  "#75BCD4",
  "#73CCD5",
  "#7BD6C3",
  "#96E39E",
  "#D2CC7F",
  "#D7A77F",
  "#DB7C82",
  "#BD7DB2",
  "#9379BB",
  "#6789B9",
  "#5A9DB4",
  "#58ACB5",
  "#5FB8A5",
  "#72CC7C",
  "#BDB759",
  "#C48957",
  "#CA535A",
  "#A45C96",
  "#7458A0",
  "#496B9B",
  "#3E7F94",
  "#3D8D94",
  "#429986",
  "#4FB459",
  "#B3AC46",
  "#BB7A43",
  "#C13E46",
  "#974B89",
  "#654893",
  "#3A5C8D",
  "#316F84",
  "#307D84",
  "#348A77",
  "#3DA848",
  "#A9A132",
  "#B16A2F",
  "#B82932",
  "#8A3A7B",
  "#563886",
  "#2B4E7E",
  "#236074",
  "#226D74",
  "#267B68",
  "#2B9D37",
  "#9E961F",
  "#A85B1B",
  "#AF151E",
  "#7D2A6E",
  "#472778",
  "#1C3F70",
  "#165064",
  "#155D64",
  "#176B59",
  "#1A9126",
  "#948B0C",
  "#9E4C07",
  "#A6000A",
  "#701960",
  "#38176B",
  "#0D3061",
  "#084154",
  "#074D54",
  "#095C4A",
  "#088515",
];

export const breakdownsShorts = {
  "Global Workspace": "GNW",
  "Integrated Information": "IIT",
  "Higher Order Thought": "HOT",
  "First Order & Predictive Processing": "RPT",
  Other: "Other",
};

export const graphsHeaders = [
  {
    text: "Parameter Distribution Free Queries",
    color: "yellow",
    icon: <ParameterDist />,
    tooltip:
      "The graph depicts the distribution of parameter values, according to your specifications.",
    route: "/parameter-distribution-free-queries",
    figureLine: "",
    figureText:
      "Here, you can use the toolbar on the left to create your own queries. Select a specific parameter of interest to see how the experiments in the database distribute over the different levels of that parameter. You can also filter the results according to various parameters. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Theories Comparison",
    tooltip:
      "The graph depicts the different distributions of parameters for the four theories separately.",
    color: "orange",
    icon: <TheoriesComparison />,
    route: "theories-comparison",
    figureLine: "",
    figureText:
      "Here, you can select a specific parameter of interest, and see how the experiments referring to each one of the theories distribute over the different levels of that parameter. You can choose whether to see this distribution for experiments that supported one or more of these theories or challenged them.You can also filter the results according to consciousness type, reporting technique, and whether the study was theory-driven or not. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Parameter Distribution Bar",
    tooltip:
      'The graph depicts the distribution of different parameters for each selected theory, separated to experiments challenging ("Against") and supporting ("Pro") the theory.',
    icon: <ParameterDist2 />,
    color: "pink",
    route: "/parameter-distribution-bar",
    figureLine: "",
    figureText:
      "Here, you can select a specific theory family and a specific parameter of interest, to explore how experiments in the database that refer to the chosen theory family distribute over the different levels of the chosen parameter. The results will be shown separately for experiments supporting (blue bars) vs. challenging (red bars) the chosen theory family. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.You can also filter the results according to reporting technique.",
  },
  {
    text: "Parameter Distribution Pie",
    tooltip:
      "The inner circle of the pie chart depicts the distribution of different parameters acorss theories, The outer circle describes the distribution of each inner slice to theories.",
    icon: <ParameterTheory />,
    color: "lilac",
    route: "/parameter-distribution-pie",
    figureLine: "",
    figureText:
      "Here, you can select a specific parameter of interest, to explore how the different levels of the chosen parameter distribute across the different theories. The inner circle of the pie describes the distribution of different levels across theories,while the outer circle describes the distribution of the theory families for each inner slice. By clicking on an inner circle slice, you can generate a new pie chart focusing on that category only (reversible by re-clicking on the slice).You can also filter the results according to consciousness type, reporting technique, and ‎whether the study was theory-driven or not.‎ Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Trends Across The Years",
    tooltip:
      "The graph depicts the cumulative distribution of experiments according to the selected parameter values over time.",
    icon: <Trends />,
    color: "purple",
    route: "/across-the-years",
    figureLine: "",
    figureText:
      "Here, you can select a specific parameter of interest, and see how the experiments in the database distribute over the different levels of that parameter over time. The plot is a cumulative figure that shows the number of experiments per level at each point in time. You can also filter the results according to consciousness type and reporting technique. Note: This plot is dynamic: by clicking on one of the labels on the right side of the figure, you can hide the data related to the clicked label (reversible by re-clicking on the label). Hovering on each point in time shows you the number of experiments of that feature of interest up until that year. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Theory Driven",
    tooltip:
      "The inner circle of the pie chart depicts the distribution of experiments divided into the categories: “Theory-Driven”, “Mentioning” or “Post hoc”",
    icon: <TheoryDriven />,
    color: "navyBlue",
    route: "/theory-driven",
    figureLine: "",
    figureText:
      "Here, you can see how the experiments in the database distribute with respect to their theoretical motivation: the category 'Theory driven' includes experiments that were a-priory designed to test the predictions of at least one theory. The category 'Mentioning' includes experiments that mentioned at least one family of theories in the introduction. The category 'Post hoc' includes experiments that only interpreted their results in light of the theories.<br/> The outer circle describes the distribution of the interpretations of each experiment in the inner circle slice according to the four families of theories. By clicking on an inner circle slice, you can generate a new pie chart focusing on that category only (reversible by re-clicking on the slice). Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Timings",
    tooltip:
      "The chart depicts the findings in the temporal domain of the experiments in the database.",
    icon: <Timings />,
    color: "darkTeal",
    route: "/timings",
    figureLine: "",
    figureText:
      "Here, you can plot the time windows over which effects were reported in all experiments in the database that employed a time-resolved technique. Each horizontal line represents a specific component, colored according to its classification by the authors (see the legend). Darker colors indicate later components. Components for which a time window was given are depicted as a continuous line spanning over the components range. Dots depict components for which only the peak was reported. <br/> In this figure, you can select a specific technique/component or multi-select more than one. In addition, you can filter the results according to consciousness type and reporting technique, and theory family. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Frequencies",
    tooltip:
      "The chart depicts the findings in the frequency domain of the experiments in the database.",
    icon: <Frequencies />,
    color: "teal",
    route: "/frequencies",
    figureLine: "",
    figureText:
      "Here, you can plot the frequencies in which effects were reported in all experiments in the database that employed a time-resolved technique. Each horizontal line represents the frequency band reported in a specific experiment, colored according to its classification by the authors (see the legend). Darker colors indicate lower frequencies. Cases in which a specific frequency was reported (e.g., 5Hz), are represented by dots. In this figure, you can select a specific technique or multi-select more than one. You can also filter the results according to consciousness type, reporting technique, and theory family. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
  {
    text: "Anatomical Findings",
    tooltip:
      "The figure depicts the findings in the spatial domain of the experiments in the database which used fMRI.",
    icon: <AnatomicalFindings />,
    color: "lightTeal",
    route: "/",
    figureLine: "",
    figureText:
      "Here, you can see the findings in the spatial domain, of the experiments in the database which used fMRI. Red, yellow, blue, and green activations represent experiments supporting the global workspace theories, integrated information, higher order, and re-entry and predictive processing theories, respectively. The intensity of the color of each activation indicates the relative frequency of the activation in each brain area, within the findings supporting each theory family. Note that this does not include any statistical analysis of the data, just a simple “vote count” of the number of experiments in which a specific area was reported. ",
  },
  {
    text: "Journals",
    tooltip:
      "The bar chart depicts distribution of experiments according to the journals they were published in.",
    icon: <Journals />,
    color: "lightGreen",
    route: "/journals",
    figureLine: "",
    figureText:
      "Here, you can see in which journals the experiments in the database for a chosen theory family were reported. You can also filter the results according to consciousness type, reporting technique, and also whether the study was theory-driven or not. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories. ",
  },
  {
    text: "Consciousness World Map",
    tooltip:
      "Distribution of the experiments in the database according to nations extracted from author affiliations.",
    icon: <WorldMap />,
    color: "lightGreen",
    route: "/consciousness-world-map",
    figureLine: "",
    figureText:
      "Here, you can see how the different theories are supported in different countries around the world; the map presents the distribution of the experiments in the database according to nations extracted from author affiliations. The radius of each concentric circle describes the number of experiments supporting each theory family. You can choose a specific theory family or multi-select many.You can also filter the results according to consciousness type, reporting technique, and also whether the study was theory-driven or not. Using the ‘Minimum number of experiments’ scale you can limit the size of the presented categories.",
  },
];

export const available_populations = [
  {
    value: "heathy Adults",
    label: "Heathy Adults",
  },
  {
    value: "patients",
    label: "Patients",
  },
  {
    value: "healthy college students",
    label: "Healthy College Students",
  },
  {
    value: "non-human",
    label: "Non-human",
  },
  {
    value: "children",
    label: "Children",
  },
  {
    value: "computer",
    label: "Computer",
  },
];
import Liad from "../assets/images/Liad.jpg";
import Anil from "../assets/images/Anil.jpg";
import Axel from "../assets/images/Axel.jpg";
import LuciaM from "../assets/images/LuciaM.png";
import LucieC from "../assets/images/LucieC.jpg";
import Megan from "../assets/images/Megan.jpeg";
import Ned from "../assets/images/Ned.jpg";
import Steve from "../assets/images/Steve.jpg";
export const comparedTheories = {
  "Global Workspace": "Global Workspace",
  "Integrated Information": "<span> Integrated <br /> Information </span>",
  "Higher Order Thought": "<span> Higher Order <br /> Thought </span> ",
  "First Order & Predictive Processing":
    "<span> First Order & <br /> Predictive <br /> Processing </span>",
};

export const foundingBoardBios = [
  {
    name: "Liad Mudrik",
    image: Liad,
    text: "School of Psychological Sciences and Sagol School of Neuroscience,Tel Aviv University.",
    website: "https://mudriklab.tau.ac.il",
  },
  {
    name: "Stephen Fleming",
    image: Steve,
    title: "Professor of Cognitive Neuroscience",
    text: "University College London",
    website: "https://metacoglab.org/",
  },
  {
    name: "Megan Peters",
    image: Megan,
    text: "Department of Cognitive Sciences, University of California Irvine",
    website: "https://faculty.sites.uci.edu/cnclab",
  },
  {
    name: "Anil Seth",
    image: Anil,
    text: "Sussex Centre for Consciousness Science and Canadian Institute for Advanced Research, Program on Brain, Mind, and Consciousness",
    website: "https://www.anilseth.com",
  },
  {
    name: "Axel Cleeremans",
    image: Axel,
    title: "Director",
    text: "Center for Research in Cognition & Neurosciences, Université libre de Bruxelles (BELGIUM)",
    website: "https://axc.ulb.be/",
  },
  {
    name: "Lucie Charles",
    image: LucieC,
    text: "	Department of Psychology, Queen Mary University of London",
    website: "https://sites.google.com/site/luciecharlesneuro/home?pli=1",
  },
  {
    name: "Lucia Melloni",
    image: LuciaM,
    text: "Neural Circuits, Consciousness, and Cognition Research Group, Max Planck Institute for Empirical Aesthetics, Germany Department of Neurology, NYU Grossman School of Medicine, US",
    website:
      "https://www.aesthetics.mpg.de/en/research/research-group-neural-circuits-consciousness-and-cognition.html ",
  },
  {
    name: "Ned Block",
    image: Ned,
    title: "Silver Professor",
    text: "Departments of Philosophy, Psychology, and Center for Neural Science New York University",
    website: "https://www.nedblock.us",
  },
];
